site_name: Vortx Documentation
site_description: Documentation for the Vortx AGI Earth Memory System
site_author: Vortx Team
repo_url: https://github.com/vortx-ai/vortx
repo_name: vortx-ai/vortx

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
  - mkdocs-jupyter

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
    - Configuration: configuration.md
    - Examples: examples/index.md
  - Core Concepts:
    - Overview: core-concepts/overview.md
    - AGI Memory System:
      - Architecture: technical/agi-memory-inference.md
      - Memory Types: core-concepts/memory-types.md
      - Memory Formation: core-concepts/memory-formation.md
      - Memory Retrieval: core-concepts/memory-retrieval.md
    - Inference System:
      - Overview: core-concepts/inference-overview.md
      - Visualization: technical/inference-visualization.md
      - Performance: technical/memory-performance.md
    - Privacy & Security:
      - Overview: security/overview.md
      - Data Privacy: security/data-privacy.md
      - Access Control: security/access-control.md
  - API Reference:
    - REST API: api/rest.md
    - Python API: api/python.md
    - CLI: api/cli.md
  - Advanced Topics:
    - Distributed Computing: advanced/distributed.md
    - GPU Acceleration: advanced/gpu.md
    - Custom Models: advanced/custom-models.md
    - Performance Tuning: advanced/performance.md
  - Development:
    - Contributing: contributing.md
    - Development Setup: development/setup.md
    - Testing: development/testing.md
    - Documentation: development/documentation.md
  - Tutorials:
    - Basic Usage: tutorials/basic.md
    - Advanced Features: tutorials/advanced.md
    - Integration Guide: tutorials/integration.md
  - Reference:
    - Configuration Options: reference/configuration.md
    - Environment Variables: reference/environment.md
    - Error Codes: reference/errors.md
  - Support:
    - FAQ: support/faq.md
    - Troubleshooting: support/troubleshooting.md
    - Community: support/community.md
  - About:
    - Release Notes: about/changelog.md
    - Roadmap: about/roadmap.md
    - License: about/license.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vortx-ai/vortx
    - icon: fontawesome/brands/discord
      link: https://discord.gg/vortx
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/vortxai

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js 