# Model Configuration
stable_diffusion_model: "CompVis/stable-diffusion-v1-4"
controlnet_model: "lllyasviel/sd-controlnet-canny"
segmentation_model: "nvidia/segformer-b0-finetuned-ade-512-512"

# Image Processing
tile_size: 512
batch_size: 4
num_inference_steps: 50
guidance_scale: 7.5

# System Settings
device: "cpu"  # or "cuda" if GPU available
num_workers: 4
memory_limit: 0.9

# Output Settings
output_format: "png"
output_quality: 95
max_resolution: 2048

# Cache Settings
cache_enabled: true
cache_dir: "cache"
max_cache_size: 1000
